### ISSUE TITLE
Core crashes if a plugin doesn't implement CustomCommands()

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/aspect-cli#161]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x9cb840]

goroutine 1 [running]:
aspect.build/cli/pkg/plugin/sdk/v1alpha2/plugin.(*GRPCClient).CustomCommands(0xc0003b0108)
	pkg/plugin/sdk/v1alpha2/plugin/grpc.go:224 +0x80
aspect.build/cli/pkg/plugin/system.(*pluginSystem).RegisterCustomCommands(0xc00012a050, 0xc00016c280)
	pkg/plugin/system/system.go:116 +0x19f
main.main()
	cmd/aspect/main.go:52 +0x28c
```

**Comment by alexeagle** [comment]
We're going to rewrite the plugin API
